import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "@/app/a_components/Navbar"
import { Home, Search, SquarePlus, User } from "lucide-react";

export const metadata: Metadata = {
  title: "L'EntreDeux",
  description: "Generated by create next app",
};

const items = [
  {
    lucide: <Home />,
    link: "/"
  },
  {
    lucide: <Search />,
    link: "/"
  },
  {
    lucide: <SquarePlus />,
    link: "/"
  },
  {
    lucide: <User />,
    link: "/"
  }
]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Navbar items={items} />
        {children}
      </body>
    </html>
  );
}
